name: gamming_community
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^0.17.4
  cached_network_image: ^2.0.0
  flutter_launcher_icons: ^0.7.4
  bot_toast: ^2.4.1
  flutter_webrtc: ^0.2.7
  graphql_flutter: ^3.1.0-beta.3
  carousel_slider: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  shared_preferences: ^0.5.7
  pull_to_refresh: ^1.5.7
  provider: ^4.0.5
  socket_io_client: ^0.9.9
  states_rebuilder: ^1.15.0
  intl: ^0.16.1
  video_player: ^0.10.8+1
  chewie: ^0.9.10
  image_picker: ^0.6.3+4
  dotted_border: ^1.0.5
  flutter_local_notifications: ^1.4.1
  page_transition: ^1.1.5
  google_nav_bar: ^2.1.0
  tuple: ^1.0.3
  rxdart: ^0.23.1
  # json webtoken 
  jose: ^0.1.2+1
  palette_generator: ^0.2.2
  responsive_widgets: ^2.0.1
  optimized_cached_image: ^0.1.7
  feather_icons_flutter: ^4.7.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
dependency_overrides: 
  path: 1.7.0 

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  
flutter_icons:
  image_path: "assets/images/launcher_icon/logo.png"
  android: true

flutter:
  uses-material-design: true
  assets:
      - assets/loading/
      - assets/icons/article_logo/
      - assets/icons/logo/
      - assets/icons/platforms/
      - assets/categories/
      - assets/images/
      - assets/icons/
      - assets/


  fonts:
  - family: GoogleSans-Regular     
    fonts:
    - asset: fonts/ProductSans-Regular.ttf
   
  - family: GoogleSans-Bold     
    fonts:
    - asset: fonts/ProductSans-Bold.ttf
  - family: GoogleSans-Italic
    fonts:
    - asset: fonts/ProductSans-Italic.ttf
  - family: GoogleSans-Bold-Italic
    fonts:
    - asset: fonts/ProductSans-Bold-Italic.ttf
