name: gamming_community
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^0.15.0
  cached_network_image: ^2.0.0
  flutter_launcher_icons: ^0.7.4
  bot_toast: ^2.2.1
  bottom_navy_bar: ^5.3.2
  open_iconic_flutter: ^0.3.0
  flutter_webrtc: ^0.2.2
  graphql_flutter: ^3.0.1-beta.1
  carousel_slider: ^1.4.1
  flutter_spinkit: ^4.1.2
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  shared_preferences: ^0.5.6+3
  pull_to_refresh: ^1.5.7
  provider: ^4.0.4
  socket_io_client: ^0.9.9
  states_rebuilder: ^1.14.0
  intl: ^0.16.1
  incrementally_loading_listview: ^0.3.0
  video_player: ^0.10.8+1
  chewie: ^0.9.10
  shimmer: ^1.1.0
  image_picker: ^0.6.3+4
  dotted_border: ^1.0.5
  flutter_local_notifications: ^1.3.0
  page_transition: ^1.1.5
  google_nav_bar: ^2.1.0
  tuple: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  image_path: "assets/images/launcher_icon/logo.png"
  android: true

flutter:
  uses-material-design: true
  assets:
      - assets/icons/article_logo/
      - assets/icons/logo/
      - assets/icons/platforms/
      - assets/categories/
      - assets/images/
      - assets/icons/
      - assets/


  fonts:
  - family: GoogleSans-Regular     
    fonts:
    - asset: fonts/ProductSans-Regular.ttf
   
  - family: GoogleSans-Medium     
    fonts:
    - asset: fonts/ProductSans-Medium.ttf
  - family: GoogleSans-Italic
    fonts:
    - asset: fonts/ProductSans-Italic.ttf
  - family: GoogleSans-Light
    fonts:
    - asset: fonts/ProductSans-Light.ttf
  - family: GoogleSans-Bold
    fonts:
    - asset: fonts/ProductSans-Bold.ttf
